name: Karma tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Job Setup
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #Checkout Repo
      - uses: actions/setup-node@v4 #Setup Node
        with:
          node-version: 20
      - uses: browser-actions/setup-edge@v1
      - name: Run Karma Tests
        run: |
          npm i
          npm run test
