name: Karma tests

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

# Job Setup
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4 #Checkout Repo
      - uses: actions/setup-node@v4 #Setup Node
        with:
          node-version: 20
      - name: Install Microsoft Edge
        run: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft-archive-keyring.gpg && sudo mv microsoft-archive-keyring.gpg /usr/share/keyrings/ && echo "deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/edge stable main" | sudo tee /etc/apt/sources.list.d/microsoft-edge-stable.list && sudo apt update && sudo apt install -y microsoft-edge-stable
      - name: Run Karma Tests
        run: |
          npm i
          npm run test
